openapi: 3.1.0
info:
  title: Documentación de e-commerce - Carts
  description: Documentación de endpoints de carts
  version: 1.0.0

paths:
  /api/carts:
    post:
      tags:
        - Carts
      summary: Crear un carrito
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                products:
                  type: array
                  items:
                    type: string
      responses:
        201:
          description: Carrito creado
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                  message:
                    type: string
                  data:
                    $ref: "#/components/schemas/Cart"
        400:
          description: Datos inválidos o faltantes

  /api/carts/{cartId}:
    get:
      tags:
        - Carts
      summary: Obtener un carrito por ID
      parameters:
        - name: cartId
          in: path
          required: true
          description: ID del carrito
          schema:
            type: string
      responses:
        200:
          description: Detalle del carrito
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cart"
        404:
          description: Carrito no encontrado
    put:
      tags:
        - Carts
      summary: Actualizar un carrito
      parameters:
        - name: cartId
          in: path
          required: true
          description: ID del carrito
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Cart"
      responses:
        200:
          description: Carrito actualizado
        404:
          description: Carrito no encontrado
    delete:
      tags:
        - Carts
      summary: Limpiar carrito
      parameters:
        - name: cartId
          in: path
          required: true
          description: ID del carrito
          schema:
            type: string
      responses:
        200:
          description: Carrito limpiado
        404:
          description: Carrito no encontrado

  /api/carts/{cartId}/purchase:
    post:
      tags:
        - Carts
      summary: Finalizar compra
      security:
        - sessionAuth: []
      parameters:
        - name: cartId
          in: path
          required: true
          description: ID del carrito
          schema:
            type: string
      responses:
        200:
          description: Compra finalizada

  /api/carts/{cartId}/products/{productId}:
    post:
      tags:
        - Carts
      summary: Agregar un producto al carrito
      security:
        - sessionAuth: []
      parameters:
        - name: cartId
          in: path
          required: true
          description: ID del carrito
          schema:
            type: string
        - name: productId
          in: path
          required: true
          description: ID del producto
          schema:
            type: string
      responses:
        201:
          description: Producto agregado
        404:
          description: Carrito o producto no encontrado
    delete:
      tags:
        - Carts
      summary: Remover un producto del carrito
      parameters:
        - name: cartId
          in: path
          required: true
          description: ID del carrito
          schema:
            type: string
        - name: productId
          in: path
          required: true
          description: ID del producto
          schema:
            type: string
      responses:
        200:
          description: Producto eliminado
        404:
          description: Carrito o producto no encontrado
    put:
      tags:
        - Carts
      summary: Actualizar cantidad de un producto en el carrito
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                quantity:
                  type: integer
      responses:
        200:
          description: Cantidad actualizada
        404:
          description: Carrito o producto no encontrado

components:
  schemas:
    Cart:
      type: object
      properties:
        products:
          type: array
          items:
            type: string

security:
  sessionAuth:
    type: apiKey
    in: cookie
    name: sessionId
